version: '3.7'
services:
  redis:
    image: redis:4-alpine
    ports:
      - 6379:6379
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - './tmp/mysql:/var/lib/mysql'
  aws-local:
    image: localstack/localstack
    ports:
      - '4567-4583:4567-4583'
      - '8080:8080'
    environment:
      - SERVICES=lambda,sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
    volumes:
      - "${PWD}/tmp/localstack:/tmp/localstack"
      - '/var/run/docker.sock:/var/run/docker.sock'
