version: '3.7'
services:
  redis:
    image: redis:4-alpine
    ports:
      - 6379:6379
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  aws-local:
    image: localstack/localstack
    ports:
      - '4567-4583:4567-4583'
      - '8080:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack
      - PORT_WEB_UI=8080
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=ap-southeast-1
      - S3_BACKEND=https://s3.ap-southeast-1.amazonaws.com
    volumes:
      - '/tmp/localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
