version: '3.7'
services:
  web:
    image: kieronqtran/cogri-vocabulary-fe
    container_name: cogri-vocabulary-fe
    build:
      context: client
      dockerfile: Dockerfile
      target: production
    env_file:
      - ./client/docker.env
    environment:
      - CONTEXT=angular-ngrx-material-starter
      - PORT=4200
    ports:
      - '4200:4200'
  api:
    image: kieronqtran/cogri-vocabulary-api
    build:
      context: server
      dockerfile: Dockerfile
      target: production
    env_file:
      - ./server/docker.env
    environment:
     - NODE_ENV=production
