version: '3.7'
services:
  web:
    image: kieronqtran/cogri-vocabulary-fe
    container_name: cogri-vocabulary-fe
    build:
      context: client
      dockerfile: Dockerfile
      target: production
    env_file:
      - ./client/docker.env
    environment:
      - CONTEXT=angular-ngrx-material-starter
      - PORT=4200
    ports:
      - '4200:4200'
  word:
    image: kieronqtran/cogri-vocabulary-word
    build:
      context: word
      dockerfile: Dockerfile
      target: production
    env_file:
      - word/docker.env
    environment:
     - NODE_ENV=production

  learner:
    image: kieronqtran/cogri-vocabulary-learner
    build:
      context: learner
      dockerfile: Dockerfile
      target: production
    env_file:
      - leaner/docker.env
    environment:
      - NODE_ENV=production
